/*
 * File:           C:\Users\mikbi\Documents\Allegati\Desktop\Sigmastudio\DigiRadioFinale_IC_1_PARAM.h
 *
 * Created:        Tuesday, August 25, 2026 8:11:05 PM
 * Description:    DigiRadioFinale:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2026 Analog Devices, Inc. All rights reserved.
 */
#ifndef __DIGIRADIOFINALE_IC_1_PARAM_H__
#define __DIGIRADIOFINALE_IC_1_PARAM_H__


/* Module Beep1 - Beep Sources*/
#define COUNT_BEEP1                                    3
#define DEVICE_BEEP1                                   "IC1"
#define ADDR_BEEP1_ENABLE                              0
#define FIXPT_BEEP1_ENABLE                             0x00000000
#define VALUE_BEEP1_ENABLE                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_BEEP1_ENABLE                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BEEP1_KICK                                1
#define FIXPT_BEEP1_KICK                               0x00000000
#define VALUE_BEEP1_KICK                               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_BEEP1_KICK                                SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BEEP1_BEEP_FREQ                           2
#define FIXPT_BEEP1_BEEP_FREQ                          0x00006CAB
#define VALUE_BEEP1_BEEP_FREQ                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00331636677280911)
#define TYPE_BEEP1_BEEP_FREQ                           SIGMASTUDIOTYPE_FIXPOINT

/* Module DC1 - DC Input Entry*/
#define COUNT_DC1                                      1
#define DEVICE_DC1                                     "IC1"
#define ADDR_DC1                                       3
#define FIXPT_DC1                                      0x00800000
#define VALUE_DC1                                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_DC1                                       SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB1 - DC Blocking*/
#define COUNT_DCB1                                     1
#define DEVICE_DCB1                                    "IC1"
#define ADDR_DCB1_POLE                                 4
#define FIXPT_DCB1_POLE                                0x007FFCB9
#define VALUE_DCB1_POLE                                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define TYPE_DCB1_POLE                                 SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB2 - DC Blocking*/
#define COUNT_DCB2                                     1
#define DEVICE_DCB2                                    "IC1"
#define ADDR_DCB2_POLE                                 5
#define FIXPT_DCB2_POLE                                0x007FFCB9
#define VALUE_DCB2_POLE                                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define TYPE_DCB2_POLE                                 SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB4 - DC Blocking*/
#define COUNT_DCB4                                     1
#define DEVICE_DCB4                                    "IC1"
#define ADDR_DCB4_POLE                                 6
#define FIXPT_DCB4_POLE                                0x007FFCB9
#define VALUE_DCB4_POLE                                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define TYPE_DCB4_POLE                                 SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB3 - DC Blocking*/
#define COUNT_DCB3                                     1
#define DEVICE_DCB3                                    "IC1"
#define ADDR_DCB3_POLE                                 7
#define FIXPT_DCB3_POLE                                0x007FFCB9
#define VALUE_DCB3_POLE                                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define TYPE_DCB3_POLE                                 SIGMASTUDIOTYPE_FIXPOINT

/* Module S Splitter1 - Single Control Splitter*/
#define COUNT_SSPLITTER1                               1
#define DEVICE_SSPLITTER1                              "IC1"
#define ADDR_SSPLITTER1                                8
#define FIXPT_SSPLITTER1                               0x0141857E
#define VALUE_SSPLITTER1                               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.51188643150958)
#define TYPE_SSPLITTER1                                SIGMASTUDIOTYPE_FIXPOINT

/* Module Compressor1 - RMS (gain)*/
#define COUNT_COMPRESSOR1                              38
#define DEVICE_COMPRESSOR1                             "IC1"
#define ADDR_COMPRESSOR1_0                             9
#define FIXPT_COMPRESSOR1_0                            0x00090FCB
#define VALUE_COMPRESSOR1_0                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0707945784384138)
#define TYPE_COMPRESSOR1_0                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_1                             10
#define FIXPT_COMPRESSOR1_1                            0x00090FCB
#define VALUE_COMPRESSOR1_1                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0707945784384138)
#define TYPE_COMPRESSOR1_1                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_2                             11
#define FIXPT_COMPRESSOR1_2                            0x00066A4A
#define VALUE_COMPRESSOR1_2                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0501187233627272)
#define TYPE_COMPRESSOR1_2                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_3                             12
#define FIXPT_COMPRESSOR1_3                            0x00048AA7
#define VALUE_COMPRESSOR1_3                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0354813389233576)
#define TYPE_COMPRESSOR1_3                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_4                             13
#define FIXPT_COMPRESSOR1_4                            0x00033718
#define VALUE_COMPRESSOR1_4                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0251188643150958)
#define TYPE_COMPRESSOR1_4                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_5                             14
#define FIXPT_COMPRESSOR1_5                            0x000246B4
#define VALUE_COMPRESSOR1_5                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0177827941003892)
#define TYPE_COMPRESSOR1_5                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_6                             15
#define FIXPT_COMPRESSOR1_6                            0x00019C86
#define VALUE_COMPRESSOR1_6                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0125892541179417)
#define TYPE_COMPRESSOR1_6                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_7                             16
#define FIXPT_COMPRESSOR1_7                            0x0001240B
#define VALUE_COMPRESSOR1_7                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00891250938133746)
#define TYPE_COMPRESSOR1_7                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_8                             17
#define FIXPT_COMPRESSOR1_8                            0x0000CEC0
#define VALUE_COMPRESSOR1_8                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00630957344480193)
#define TYPE_COMPRESSOR1_8                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_9                             18
#define FIXPT_COMPRESSOR1_9                            0x0000925E
#define VALUE_COMPRESSOR1_9                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00446683592150963)
#define TYPE_COMPRESSOR1_9                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_10                            19
#define FIXPT_COMPRESSOR1_10                           0x0000679F
#define VALUE_COMPRESSOR1_10                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00316227766016838)
#define TYPE_COMPRESSOR1_10                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_11                            20
#define FIXPT_COMPRESSOR1_11                           0x0000495B
#define VALUE_COMPRESSOR1_11                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00223872118189122)
#define TYPE_COMPRESSOR1_11                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_12                            21
#define FIXPT_COMPRESSOR1_12                           0x0000DAD7
#define VALUE_COMPRESSOR1_12                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0066784843631956)
#define TYPE_COMPRESSOR1_12                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_13                            22
#define FIXPT_COMPRESSOR1_13                           0x0002FD85
#define VALUE_COMPRESSOR1_13                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.023361914765363)
#define TYPE_COMPRESSOR1_13                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_14                            23
#define FIXPT_COMPRESSOR1_14                           0x000A75DD
#define VALUE_COMPRESSOR1_14                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0817219943662389)
#define TYPE_COMPRESSOR1_14                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_15                            24
#define FIXPT_COMPRESSOR1_15                           0x00249768
#define VALUE_COMPRESSOR1_15                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.285870590243626)
#define TYPE_COMPRESSOR1_15                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_16                            25
#define FIXPT_COMPRESSOR1_16                           0x007EDA4C
#define VALUE_COMPRESSOR1_16                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.991036968711138)
#define TYPE_COMPRESSOR1_16                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_17                            26
#define FIXPT_COMPRESSOR1_17                           0x00800000
#define VALUE_COMPRESSOR1_17                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_17                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_18                            27
#define FIXPT_COMPRESSOR1_18                           0x00800000
#define VALUE_COMPRESSOR1_18                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_18                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_19                            28
#define FIXPT_COMPRESSOR1_19                           0x00800000
#define VALUE_COMPRESSOR1_19                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_19                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_20                            29
#define FIXPT_COMPRESSOR1_20                           0x00800000
#define VALUE_COMPRESSOR1_20                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_20                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_21                            30
#define FIXPT_COMPRESSOR1_21                           0x00800000
#define VALUE_COMPRESSOR1_21                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_21                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_22                            31
#define FIXPT_COMPRESSOR1_22                           0x00800000
#define VALUE_COMPRESSOR1_22                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_22                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_23                            32
#define FIXPT_COMPRESSOR1_23                           0x00800000
#define VALUE_COMPRESSOR1_23                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_23                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_24                            33
#define FIXPT_COMPRESSOR1_24                           0x00800000
#define VALUE_COMPRESSOR1_24                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_24                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_25                            34
#define FIXPT_COMPRESSOR1_25                           0x00800000
#define VALUE_COMPRESSOR1_25                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_25                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_26                            35
#define FIXPT_COMPRESSOR1_26                           0x00800000
#define VALUE_COMPRESSOR1_26                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_26                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_27                            36
#define FIXPT_COMPRESSOR1_27                           0x00800000
#define VALUE_COMPRESSOR1_27                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_27                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_28                            37
#define FIXPT_COMPRESSOR1_28                           0x00800000
#define VALUE_COMPRESSOR1_28                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_28                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_29                            38
#define FIXPT_COMPRESSOR1_29                           0x00800000
#define VALUE_COMPRESSOR1_29                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_29                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_30                            39
#define FIXPT_COMPRESSOR1_30                           0x00800000
#define VALUE_COMPRESSOR1_30                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_30                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_31                            40
#define FIXPT_COMPRESSOR1_31                           0x00800000
#define VALUE_COMPRESSOR1_31                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_31                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_32                            41
#define FIXPT_COMPRESSOR1_32                           0x00800000
#define VALUE_COMPRESSOR1_32                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_32                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_33                            42
#define FIXPT_COMPRESSOR1_33                           0x00800000
#define VALUE_COMPRESSOR1_33                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_33                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_RMS                           43
#define FIXPT_COMPRESSOR1_RMS                          0x00000FB9
#define VALUE_COMPRESSOR1_RMS                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000479820304660095)
#define TYPE_COMPRESSOR1_RMS                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_POST_GAIN                     44
#define FIXPT_COMPRESSOR1_POST_GAIN                    0x00800000
#define VALUE_COMPRESSOR1_POST_GAIN                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_COMPRESSOR1_POST_GAIN                     SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_COMPRESSOR1_HOLD                          45
#define FIXPT_COMPRESSOR1_HOLD                         0x00000960
#define VALUE_COMPRESSOR1_HOLD                         SIGMASTUDIOTYPE_INTEGER_CONVERT(2400)
#define TYPE_COMPRESSOR1_HOLD                          SIGMASTUDIOTYPE_INTEGER
#define ADDR_COMPRESSOR1_DECAY                         46
#define FIXPT_COMPRESSOR1_DECAY                        0x000000B6
#define VALUE_COMPRESSOR1_DECAY                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.17013888888889E-05)
#define TYPE_COMPRESSOR1_DECAY                         SIGMASTUDIOTYPE_FIXPOINT

/* Module 1 X RTA3 - Single Level Detector*/
#define COUNT_1XRTA3                                   5
#define DEVICE_1XRTA3                                  "IC1"
#define ADDR_1XRTA3_TCONST                             47
#define FIXPT_1XRTA3_TCONST                            0x00004EB0
#define VALUE_1XRTA3_TCONST                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define TYPE_1XRTA3_TCONST                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA3_HOLD                               48
#define FIXPT_1XRTA3_HOLD                              0x000001E0
#define VALUE_1XRTA3_HOLD                              SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define TYPE_1XRTA3_HOLD                               SIGMASTUDIOTYPE_INTEGER
#define ADDR_1XRTA3_DECAY                              49
#define FIXPT_1XRTA3_DECAY                             0x0000071C
#define VALUE_1XRTA3_DECAY                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define TYPE_1XRTA3_DECAY                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA3                                    2074
#define VALUES_1XRTA3                                  SIGMASTUDIOTYPE_SPECIAL(0x026E)
#define TYPE_1XRTA3                                    SIGMASTUDIOTYPE_SPECIAL
#define ADDR_1XRTA3                                    2074
#define VALUE_1XRTA3                                   SIGMASTUDIOTYPE_10_14_CONVERT(0)
#define TYPE_1XRTA3                                    SIGMASTUDIOTYPE_10_14

/* Module 1 X RTA4 - Single Level Detector*/
#define COUNT_1XRTA4                                   5
#define DEVICE_1XRTA4                                  "IC1"
#define ADDR_1XRTA4_TCONST                             50
#define FIXPT_1XRTA4_TCONST                            0x00004EB0
#define VALUE_1XRTA4_TCONST                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define TYPE_1XRTA4_TCONST                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA4_HOLD                               51
#define FIXPT_1XRTA4_HOLD                              0x000001E0
#define VALUE_1XRTA4_HOLD                              SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define TYPE_1XRTA4_HOLD                               SIGMASTUDIOTYPE_INTEGER
#define ADDR_1XRTA4_DECAY                              52
#define FIXPT_1XRTA4_DECAY                             0x0000071C
#define VALUE_1XRTA4_DECAY                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define TYPE_1XRTA4_DECAY                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA4                                    2074
#define VALUES_1XRTA4                                  SIGMASTUDIOTYPE_SPECIAL(0x02F2)
#define TYPE_1XRTA4                                    SIGMASTUDIOTYPE_SPECIAL
#define ADDR_1XRTA4                                    2074
#define VALUE_1XRTA4                                   SIGMASTUDIOTYPE_10_14_CONVERT(0)
#define TYPE_1XRTA4                                    SIGMASTUDIOTYPE_10_14

/* Module 1 X RTA1 - Single Level Detector*/
#define COUNT_1XRTA1                                   5
#define DEVICE_1XRTA1                                  "IC1"
#define ADDR_1XRTA1_TCONST                             53
#define FIXPT_1XRTA1_TCONST                            0x00004EB0
#define VALUE_1XRTA1_TCONST                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define TYPE_1XRTA1_TCONST                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA1_HOLD                               54
#define FIXPT_1XRTA1_HOLD                              0x000001E0
#define VALUE_1XRTA1_HOLD                              SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define TYPE_1XRTA1_HOLD                               SIGMASTUDIOTYPE_INTEGER
#define ADDR_1XRTA1_DECAY                              55
#define FIXPT_1XRTA1_DECAY                             0x0000071C
#define VALUE_1XRTA1_DECAY                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define TYPE_1XRTA1_DECAY                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA1                                    2074
#define VALUES_1XRTA1                                  SIGMASTUDIOTYPE_SPECIAL(0x0376)
#define TYPE_1XRTA1                                    SIGMASTUDIOTYPE_SPECIAL
#define ADDR_1XRTA1                                    2074
#define VALUE_1XRTA1                                   SIGMASTUDIOTYPE_10_14_CONVERT(0)
#define TYPE_1XRTA1                                    SIGMASTUDIOTYPE_10_14

/* Module 1 X RTA2 - Single Level Detector*/
#define COUNT_1XRTA2                                   5
#define DEVICE_1XRTA2                                  "IC1"
#define ADDR_1XRTA2_TCONST                             56
#define FIXPT_1XRTA2_TCONST                            0x00004EB0
#define VALUE_1XRTA2_TCONST                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define TYPE_1XRTA2_TCONST                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA2_HOLD                               57
#define FIXPT_1XRTA2_HOLD                              0x000001E0
#define VALUE_1XRTA2_HOLD                              SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define TYPE_1XRTA2_HOLD                               SIGMASTUDIOTYPE_INTEGER
#define ADDR_1XRTA2_DECAY                              58
#define FIXPT_1XRTA2_DECAY                             0x0000071C
#define VALUE_1XRTA2_DECAY                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define TYPE_1XRTA2_DECAY                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA2                                    2074
#define VALUES_1XRTA2                                  SIGMASTUDIOTYPE_SPECIAL(0x03FA)
#define TYPE_1XRTA2                                    SIGMASTUDIOTYPE_SPECIAL
#define ADDR_1XRTA2                                    2074
#define VALUE_1XRTA2                                   SIGMASTUDIOTYPE_10_14_CONVERT(0)
#define TYPE_1XRTA2                                    SIGMASTUDIOTYPE_10_14

/* Module Param EQ1 - Parametric EQ*/
#define COUNT_PARAMEQ1                                 60
#define DEVICE_PARAMEQ1                                "IC1"
#define ADDR_PARAMEQ1_ST0_B0                           59
#define FIXPT_PARAMEQ1_ST0_B0                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B0                           59
#define FIXPT_PARAMEQ1_ST0_B0                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B1                           60
#define FIXPT_PARAMEQ1_ST0_B1                          0xFF007936
#define VALUE_PARAMEQ1_ST0_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.9963010223809)
#define TYPE_PARAMEQ1_ST0_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B1                           60
#define FIXPT_PARAMEQ1_ST0_B1                          0xFF007936
#define VALUE_PARAMEQ1_ST0_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.9963010223809)
#define TYPE_PARAMEQ1_ST0_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B2                           61
#define FIXPT_PARAMEQ1_ST0_B2                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B2                           61
#define FIXPT_PARAMEQ1_ST0_B2                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A0                           62
#define FIXPT_PARAMEQ1_ST0_A0                          0x00FF86AE
#define VALUE_PARAMEQ1_ST0_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99629760176912)
#define TYPE_PARAMEQ1_ST0_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A0                           62
#define FIXPT_PARAMEQ1_ST0_A0                          0x00FF86AE
#define VALUE_PARAMEQ1_ST0_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99629760176912)
#define TYPE_PARAMEQ1_ST0_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A1                           63
#define FIXPT_PARAMEQ1_ST0_A1                          0xFF807919
#define VALUE_PARAMEQ1_ST0_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.996304442992686)
#define TYPE_PARAMEQ1_ST0_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A1                           63
#define FIXPT_PARAMEQ1_ST0_A1                          0xFF807919
#define VALUE_PARAMEQ1_ST0_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.996304442992686)
#define TYPE_PARAMEQ1_ST0_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B0                           64
#define FIXPT_PARAMEQ1_ST1_B0                          0x007FE66E
#define VALUE_PARAMEQ1_ST1_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.999219758597071)
#define TYPE_PARAMEQ1_ST1_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B0                           64
#define FIXPT_PARAMEQ1_ST1_B0                          0x007FE66E
#define VALUE_PARAMEQ1_ST1_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.999219758597071)
#define TYPE_PARAMEQ1_ST1_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B1                           65
#define FIXPT_PARAMEQ1_ST1_B1                          0xFF01D7BF
#define VALUE_PARAMEQ1_ST1_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98560347007805)
#define TYPE_PARAMEQ1_ST1_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B1                           65
#define FIXPT_PARAMEQ1_ST1_B1                          0xFF01D7BF
#define VALUE_PARAMEQ1_ST1_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98560347007805)
#define TYPE_PARAMEQ1_ST1_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B2                           66
#define FIXPT_PARAMEQ1_ST1_B2                          0x007E47C2
#define VALUE_PARAMEQ1_ST1_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986564900639355)
#define TYPE_PARAMEQ1_ST1_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B2                           66
#define FIXPT_PARAMEQ1_ST1_B2                          0x007E47C2
#define VALUE_PARAMEQ1_ST1_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.986564900639355)
#define TYPE_PARAMEQ1_ST1_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A0                           67
#define FIXPT_PARAMEQ1_ST1_A0                          0x00FE2841
#define VALUE_PARAMEQ1_ST1_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98560347007805)
#define TYPE_PARAMEQ1_ST1_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A0                           67
#define FIXPT_PARAMEQ1_ST1_A0                          0x00FE2841
#define VALUE_PARAMEQ1_ST1_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98560347007805)
#define TYPE_PARAMEQ1_ST1_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A1                           68
#define FIXPT_PARAMEQ1_ST1_A1                          0xFF81D1CF
#define VALUE_PARAMEQ1_ST1_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.985784659236426)
#define TYPE_PARAMEQ1_ST1_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A1                           68
#define FIXPT_PARAMEQ1_ST1_A1                          0xFF81D1CF
#define VALUE_PARAMEQ1_ST1_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.985784659236426)
#define TYPE_PARAMEQ1_ST1_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B0                           69
#define FIXPT_PARAMEQ1_ST2_B0                          0x00800B93
#define VALUE_PARAMEQ1_ST2_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.00035324391255)
#define TYPE_PARAMEQ1_ST2_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B0                           69
#define FIXPT_PARAMEQ1_ST2_B0                          0x00800B93
#define VALUE_PARAMEQ1_ST2_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.00035324391255)
#define TYPE_PARAMEQ1_ST2_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B1                           70
#define FIXPT_PARAMEQ1_ST2_B1                          0xFF064A08
#define VALUE_PARAMEQ1_ST2_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.95086578127628)
#define TYPE_PARAMEQ1_ST2_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B1                           70
#define FIXPT_PARAMEQ1_ST2_B1                          0xFF064A08
#define VALUE_PARAMEQ1_ST2_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.95086578127628)
#define TYPE_PARAMEQ1_ST2_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B2                           71
#define FIXPT_PARAMEQ1_ST2_B2                          0x0079F533
#define VALUE_PARAMEQ1_ST2_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.952795462852717)
#define TYPE_PARAMEQ1_ST2_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B2                           71
#define FIXPT_PARAMEQ1_ST2_B2                          0x0079F533
#define VALUE_PARAMEQ1_ST2_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.952795462852717)
#define TYPE_PARAMEQ1_ST2_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A0                           72
#define FIXPT_PARAMEQ1_ST2_A0                          0x00F9B5F8
#define VALUE_PARAMEQ1_ST2_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.95086578127628)
#define TYPE_PARAMEQ1_ST2_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A0                           72
#define FIXPT_PARAMEQ1_ST2_A0                          0x00F9B5F8
#define VALUE_PARAMEQ1_ST2_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.95086578127628)
#define TYPE_PARAMEQ1_ST2_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A1                           73
#define FIXPT_PARAMEQ1_ST2_A1                          0xFF85FF3A
#define VALUE_PARAMEQ1_ST2_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.953148706765263)
#define TYPE_PARAMEQ1_ST2_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A1                           73
#define FIXPT_PARAMEQ1_ST2_A1                          0xFF85FF3A
#define VALUE_PARAMEQ1_ST2_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.953148706765263)
#define TYPE_PARAMEQ1_ST2_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B0                           74
#define FIXPT_PARAMEQ1_ST3_B0                          0x007F5D86
#define VALUE_PARAMEQ1_ST3_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.995041660660568)
#define TYPE_PARAMEQ1_ST3_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B0                           74
#define FIXPT_PARAMEQ1_ST3_B0                          0x007F5D86
#define VALUE_PARAMEQ1_ST3_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.995041660660568)
#define TYPE_PARAMEQ1_ST3_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B1                           75
#define FIXPT_PARAMEQ1_ST3_B1                          0xFF14BB23
#define VALUE_PARAMEQ1_ST3_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.83803915762905)
#define TYPE_PARAMEQ1_ST3_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B1                           75
#define FIXPT_PARAMEQ1_ST3_B1                          0xFF14BB23
#define VALUE_PARAMEQ1_ST3_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.83803915762905)
#define TYPE_PARAMEQ1_ST3_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B2                           76
#define FIXPT_PARAMEQ1_ST3_B2                          0x006E7DE9
#define VALUE_PARAMEQ1_ST3_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.863217563504857)
#define TYPE_PARAMEQ1_ST3_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B2                           76
#define FIXPT_PARAMEQ1_ST3_B2                          0x006E7DE9
#define VALUE_PARAMEQ1_ST3_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.863217563504857)
#define TYPE_PARAMEQ1_ST3_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A0                           77
#define FIXPT_PARAMEQ1_ST3_A0                          0x00EB44DD
#define VALUE_PARAMEQ1_ST3_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.83803915762905)
#define TYPE_PARAMEQ1_ST3_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A0                           77
#define FIXPT_PARAMEQ1_ST3_A0                          0x00EB44DD
#define VALUE_PARAMEQ1_ST3_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.83803915762905)
#define TYPE_PARAMEQ1_ST3_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A1                           78
#define FIXPT_PARAMEQ1_ST3_A1                          0xFF922490
#define VALUE_PARAMEQ1_ST3_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.858259224165424)
#define TYPE_PARAMEQ1_ST3_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A1                           78
#define FIXPT_PARAMEQ1_ST3_A1                          0xFF922490
#define VALUE_PARAMEQ1_ST3_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.858259224165424)
#define TYPE_PARAMEQ1_ST3_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B0                           79
#define FIXPT_PARAMEQ1_ST4_B0                          0x0080525C
#define VALUE_PARAMEQ1_ST4_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.0025135270275)
#define TYPE_PARAMEQ1_ST4_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B0                           79
#define FIXPT_PARAMEQ1_ST4_B0                          0x0080525C
#define VALUE_PARAMEQ1_ST4_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.0025135270275)
#define TYPE_PARAMEQ1_ST4_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B1                           80
#define FIXPT_PARAMEQ1_ST4_B1                          0xFF3CC491
#define VALUE_PARAMEQ1_ST4_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.52525133650548)
#define TYPE_PARAMEQ1_ST4_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B1                           80
#define FIXPT_PARAMEQ1_ST4_B1                          0xFF3CC491
#define VALUE_PARAMEQ1_ST4_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.52525133650548)
#define TYPE_PARAMEQ1_ST4_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B2                           81
#define FIXPT_PARAMEQ1_ST4_B2                          0x005501AB
#define VALUE_PARAMEQ1_ST4_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.664113447602641)
#define TYPE_PARAMEQ1_ST4_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B2                           81
#define FIXPT_PARAMEQ1_ST4_B2                          0x005501AB
#define VALUE_PARAMEQ1_ST4_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.664113447602641)
#define TYPE_PARAMEQ1_ST4_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A0                           82
#define FIXPT_PARAMEQ1_ST4_A0                          0x00C33B6F
#define VALUE_PARAMEQ1_ST4_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.52525133650548)
#define TYPE_PARAMEQ1_ST4_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A0                           82
#define FIXPT_PARAMEQ1_ST4_A0                          0x00C33B6F
#define VALUE_PARAMEQ1_ST4_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.52525133650548)
#define TYPE_PARAMEQ1_ST4_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A1                           83
#define FIXPT_PARAMEQ1_ST4_A1                          0xFFAAABF8
#define VALUE_PARAMEQ1_ST4_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.666626974630141)
#define TYPE_PARAMEQ1_ST4_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A1                           83
#define FIXPT_PARAMEQ1_ST4_A1                          0xFFAAABF8
#define VALUE_PARAMEQ1_ST4_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.666626974630141)
#define TYPE_PARAMEQ1_ST4_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B0                           84
#define FIXPT_PARAMEQ1_ST5_B0                          0x00822B9A
#define VALUE_PARAMEQ1_ST5_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.0169556566183)
#define TYPE_PARAMEQ1_ST5_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B0                           84
#define FIXPT_PARAMEQ1_ST5_B0                          0x00822B9A
#define VALUE_PARAMEQ1_ST5_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.0169556566183)
#define TYPE_PARAMEQ1_ST5_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B1                           85
#define FIXPT_PARAMEQ1_ST5_B1                          0xFF98C2B2
#define VALUE_PARAMEQ1_ST5_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.806558395910749)
#define TYPE_PARAMEQ1_ST5_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B1                           85
#define FIXPT_PARAMEQ1_ST5_B1                          0xFF98C2B2
#define VALUE_PARAMEQ1_ST5_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.806558395910749)
#define TYPE_PARAMEQ1_ST5_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B2                           86
#define FIXPT_PARAMEQ1_ST5_B2                          0x0034930B
#define VALUE_PARAMEQ1_ST5_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.410737486131021)
#define TYPE_PARAMEQ1_ST5_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B2                           86
#define FIXPT_PARAMEQ1_ST5_B2                          0x0034930B
#define VALUE_PARAMEQ1_ST5_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.410737486131021)
#define TYPE_PARAMEQ1_ST5_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A0                           87
#define FIXPT_PARAMEQ1_ST5_A0                          0x00673D4E
#define VALUE_PARAMEQ1_ST5_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.806558395910749)
#define TYPE_PARAMEQ1_ST5_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A0                           87
#define FIXPT_PARAMEQ1_ST5_A0                          0x00673D4E
#define VALUE_PARAMEQ1_ST5_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.806558395910749)
#define TYPE_PARAMEQ1_ST5_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A1                           88
#define FIXPT_PARAMEQ1_ST5_A1                          0xFFC9415A
#define VALUE_PARAMEQ1_ST5_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.427693142749325)
#define TYPE_PARAMEQ1_ST5_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A1                           88
#define FIXPT_PARAMEQ1_ST5_A1                          0xFFC9415A
#define VALUE_PARAMEQ1_ST5_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.427693142749325)
#define TYPE_PARAMEQ1_ST5_A1                           SIGMASTUDIOTYPE_FIXPOINT

/* Module SPhat1 - SuperPhat Spatializer*/
#define COUNT_SPHAT1                                   52
#define DEVICE_SPHAT1                                  "IC1"
#define ADDR_SPHAT1_B0LO0                              89
#define FIXPT_SPHAT1_B0LO0                             0x0002C477
#define VALUE_SPHAT1_B0LO0                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.021620718376497)
#define TYPE_SPHAT1_B0LO0                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO1                              90
#define FIXPT_SPHAT1_B0LO1                             0x000588EF
#define VALUE_SPHAT1_B0LO1                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.043241436752994)
#define TYPE_SPHAT1_B0LO1                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO2                              91
#define FIXPT_SPHAT1_B0LO2                             0x0002C477
#define VALUE_SPHAT1_B0LO2                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.021620718376497)
#define TYPE_SPHAT1_B0LO2                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO3                              92
#define FIXPT_SPHAT1_B0LO3                             0x00C584FE
#define VALUE_SPHAT1_B0LO3                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.54312113123739)
#define TYPE_SPHAT1_B0LO3                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO4                              93
#define FIXPT_SPHAT1_B0LO4                             0xFFAF6923
#define VALUE_SPHAT1_B0LO4                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.629604004743374)
#define TYPE_SPHAT1_B0LO4                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO5                              94
#define FIXPT_SPHAT1_B0LO5                             0x006586F6
#define VALUE_SPHAT1_B0LO5                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.79318128399519)
#define TYPE_SPHAT1_B0LO5                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO6                              95
#define FIXPT_SPHAT1_B0LO6                             0xFF34F213
#define VALUE_SPHAT1_B0LO6                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.58636256799038)
#define TYPE_SPHAT1_B0LO6                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO7                              96
#define FIXPT_SPHAT1_B0LO7                             0x006586F6
#define VALUE_SPHAT1_B0LO7                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.79318128399519)
#define TYPE_SPHAT1_B0LO7                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO8                              97
#define FIXPT_SPHAT1_B0LO8                             0x00C584FE
#define VALUE_SPHAT1_B0LO8                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.54312113123739)
#define TYPE_SPHAT1_B0LO8                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_B0LO9                              98
#define FIXPT_SPHAT1_B0LO9                             0xFFAF6923
#define VALUE_SPHAT1_B0LO9                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.629604004743374)
#define TYPE_SPHAT1_B0LO9                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_GAINHI                             99
#define FIXPT_SPHAT1_GAINHI                            0x00A66666
#define VALUE_SPHAT1_GAINHI                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.3)
#define TYPE_SPHAT1_GAINHI                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_GAINLO                             100
#define FIXPT_SPHAT1_GAINLO                            0x00733333
#define VALUE_SPHAT1_GAINLO                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9000000000004)
#define TYPE_SPHAT1_GAINLO                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_GAININV                            101
#define FIXPT_SPHAT1_GAININV                           0x006D66D6
#define VALUE_SPHAT1_GAININV                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.854700854700475)
#define TYPE_SPHAT1_GAININV                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE0                         102
#define FIXPT_SPHAT1_COMP_BASE0                        0x00800000
#define VALUE_SPHAT1_COMP_BASE0                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE0                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE1                         103
#define FIXPT_SPHAT1_COMP_BASE1                        0x00800000
#define VALUE_SPHAT1_COMP_BASE1                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE1                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE2                         104
#define FIXPT_SPHAT1_COMP_BASE2                        0x00800000
#define VALUE_SPHAT1_COMP_BASE2                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE2                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE3                         105
#define FIXPT_SPHAT1_COMP_BASE3                        0x00800000
#define VALUE_SPHAT1_COMP_BASE3                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE3                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE4                         106
#define FIXPT_SPHAT1_COMP_BASE4                        0x00800000
#define VALUE_SPHAT1_COMP_BASE4                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE4                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE5                         107
#define FIXPT_SPHAT1_COMP_BASE5                        0x00800000
#define VALUE_SPHAT1_COMP_BASE5                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE5                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE6                         108
#define FIXPT_SPHAT1_COMP_BASE6                        0x00800000
#define VALUE_SPHAT1_COMP_BASE6                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE6                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE7                         109
#define FIXPT_SPHAT1_COMP_BASE7                        0x00800000
#define VALUE_SPHAT1_COMP_BASE7                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE7                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE8                         110
#define FIXPT_SPHAT1_COMP_BASE8                        0x00800000
#define VALUE_SPHAT1_COMP_BASE8                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE8                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE9                         111
#define FIXPT_SPHAT1_COMP_BASE9                        0x00800000
#define VALUE_SPHAT1_COMP_BASE9                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE9                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE10                        112
#define FIXPT_SPHAT1_COMP_BASE10                       0x00800000
#define VALUE_SPHAT1_COMP_BASE10                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE10                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE11                        113
#define FIXPT_SPHAT1_COMP_BASE11                       0x00800000
#define VALUE_SPHAT1_COMP_BASE11                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE11                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE12                        114
#define FIXPT_SPHAT1_COMP_BASE12                       0x00800000
#define VALUE_SPHAT1_COMP_BASE12                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE12                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE13                        115
#define FIXPT_SPHAT1_COMP_BASE13                       0x00800000
#define VALUE_SPHAT1_COMP_BASE13                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE13                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE14                        116
#define FIXPT_SPHAT1_COMP_BASE14                       0x00800000
#define VALUE_SPHAT1_COMP_BASE14                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE14                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE15                        117
#define FIXPT_SPHAT1_COMP_BASE15                       0x00800000
#define VALUE_SPHAT1_COMP_BASE15                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE15                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE16                        118
#define FIXPT_SPHAT1_COMP_BASE16                       0x00800000
#define VALUE_SPHAT1_COMP_BASE16                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE16                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE17                        119
#define FIXPT_SPHAT1_COMP_BASE17                       0x00800000
#define VALUE_SPHAT1_COMP_BASE17                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE17                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE18                        120
#define FIXPT_SPHAT1_COMP_BASE18                       0x00800000
#define VALUE_SPHAT1_COMP_BASE18                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE18                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE19                        121
#define FIXPT_SPHAT1_COMP_BASE19                       0x00800000
#define VALUE_SPHAT1_COMP_BASE19                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE19                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE20                        122
#define FIXPT_SPHAT1_COMP_BASE20                       0x00800000
#define VALUE_SPHAT1_COMP_BASE20                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE20                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE21                        123
#define FIXPT_SPHAT1_COMP_BASE21                       0x00800000
#define VALUE_SPHAT1_COMP_BASE21                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE21                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE22                        124
#define FIXPT_SPHAT1_COMP_BASE22                       0x00800000
#define VALUE_SPHAT1_COMP_BASE22                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE22                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE23                        125
#define FIXPT_SPHAT1_COMP_BASE23                       0x00800000
#define VALUE_SPHAT1_COMP_BASE23                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE23                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE24                        126
#define FIXPT_SPHAT1_COMP_BASE24                       0x00800000
#define VALUE_SPHAT1_COMP_BASE24                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE24                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE25                        127
#define FIXPT_SPHAT1_COMP_BASE25                       0x00800000
#define VALUE_SPHAT1_COMP_BASE25                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE25                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE26                        128
#define FIXPT_SPHAT1_COMP_BASE26                       0x00800000
#define VALUE_SPHAT1_COMP_BASE26                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE26                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE27                        129
#define FIXPT_SPHAT1_COMP_BASE27                       0x00800000
#define VALUE_SPHAT1_COMP_BASE27                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SPHAT1_COMP_BASE27                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE28                        130
#define FIXPT_SPHAT1_COMP_BASE28                       0x0075694C
#define VALUE_SPHAT1_COMP_BASE28                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.917275905609131)
#define TYPE_SPHAT1_COMP_BASE28                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE29                        131
#define FIXPT_SPHAT1_COMP_BASE29                       0x005A9DF8
#define VALUE_SPHAT1_COMP_BASE29                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.707945823669434)
#define TYPE_SPHAT1_COMP_BASE29                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE30                        132
#define FIXPT_SPHAT1_COMP_BASE30                       0x0045EFFE
#define VALUE_SPHAT1_COMP_BASE30                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.54638659954071)
#define TYPE_SPHAT1_COMP_BASE30                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE31                        133
#define FIXPT_SPHAT1_COMP_BASE31                       0x0035FA26
#define VALUE_SPHAT1_COMP_BASE31                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.421696543693542)
#define TYPE_SPHAT1_COMP_BASE31                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE32                        134
#define FIXPT_SPHAT1_COMP_BASE32                       0x0029A8BB
#define VALUE_SPHAT1_COMP_BASE32                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.325461745262146)
#define TYPE_SPHAT1_COMP_BASE32                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_COMP_BASE33                        135
#define FIXPT_SPHAT1_COMP_BASE33                       0x002026F3
#define VALUE_SPHAT1_COMP_BASE33                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.251188635826111)
#define TYPE_SPHAT1_COMP_BASE33                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_RMS                                136
#define FIXPT_SPHAT1_RMS                               0x00064A35
#define VALUE_SPHAT1_RMS                               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0491397291363098)
#define TYPE_SPHAT1_RMS                                SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_DECAY                              137
#define FIXPT_SPHAT1_DECAY                             0x0000016C
#define VALUE_SPHAT1_DECAY                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(4.34027777777778E-05)
#define TYPE_SPHAT1_DECAY                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_HOLD                               138
#define FIXPT_SPHAT1_HOLD                              0x00005DC0
#define VALUE_SPHAT1_HOLD                              SIGMASTUDIOTYPE_INTEGER_CONVERT(24000)
#define TYPE_SPHAT1_HOLD                               SIGMASTUDIOTYPE_INTEGER
#define ADDR_SPHAT1_SPREAD1                            139
#define FIXPT_SPHAT1_SPREAD1                           0x00080D69
#define VALUE_SPHAT1_SPREAD1                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0629093159447337)
#define TYPE_SPHAT1_SPREAD1                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SPHAT1_SPREAD2                            140
#define FIXPT_SPHAT1_SPREAD2                           0x0002788C
#define VALUE_SPHAT1_SPREAD2                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0193038143874401)
#define TYPE_SPHAT1_SPREAD2                            SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter1 - General (2nd order)*/
#define COUNT_GENFILTER1                               5
#define DEVICE_GENFILTER1                              "IC1"
#define ADDR_GENFILTER1_ST0_B0                         141
#define FIXPT_GENFILTER1_ST0_B0                        0x00800000
#define VALUE_GENFILTER1_ST0_B0                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_GENFILTER1_ST0_B0                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_GENFILTER1_ST0_B1                         142
#define FIXPT_GENFILTER1_ST0_B1                        0x00000000
#define VALUE_GENFILTER1_ST0_B1                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_GENFILTER1_ST0_B1                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_GENFILTER1_ST0_B2                         143
#define FIXPT_GENFILTER1_ST0_B2                        0x00000000
#define VALUE_GENFILTER1_ST0_B2                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_GENFILTER1_ST0_B2                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_GENFILTER1_ST0_A1                         144
#define FIXPT_GENFILTER1_ST0_A1                        0x00000000
#define VALUE_GENFILTER1_ST0_A1                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_GENFILTER1_ST0_A1                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_GENFILTER1_ST0_A2                         145
#define FIXPT_GENFILTER1_ST0_A2                        0x00000000
#define VALUE_GENFILTER1_ST0_A2                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_GENFILTER1_ST0_A2                         SIGMASTUDIOTYPE_FIXPOINT

/* Module Multiple 1 - Multiple Volume Control*/
#define COUNT_MULTIPLE1                                2
#define DEVICE_MULTIPLE1                               "IC1"
#define ADDR_MULTIPLE1                                 146
#define FIXPT_MULTIPLE1                                0x00800000
#define VALUE_MULTIPLE1                                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_MULTIPLE1                                 SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_MULTIPLE1_1                               147
#define FIXPT_MULTIPLE1_1                              0x00800000
#define VALUE_MULTIPLE1_1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_MULTIPLE1_1                               SIGMASTUDIOTYPE_FIXPOINT

/* Module Bass Boost1 - Dynamic Bass Boost*/
#define COUNT_BASSBOOST1                               40
#define DEVICE_BASSBOOST1                              "IC1"
#define ADDR_BASSBOOST1_BASSFREQUENCY                  148
#define FIXPT_BASSBOOST1_BASSFREQUENCY                 0x0001015B
#define VALUE_BASSBOOST1_BASSFREQUENCY                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00785396144863598)
#define TYPE_BASSBOOST1_BASSFREQUENCY                  SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_B0                             149
#define FIXPT_BASSBOOST1_B0                            0x00000164
#define VALUE_BASSBOOST1_B0                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(4.24433093514364E-05)
#define TYPE_BASSBOOST1_B0                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_B1                             150
#define FIXPT_BASSBOOST1_B1                            0x000002C8
#define VALUE_BASSBOOST1_B1                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(8.48866187028728E-05)
#define TYPE_BASSBOOST1_B1                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_B2                             151
#define FIXPT_BASSBOOST1_B2                            0x00000164
#define VALUE_BASSBOOST1_B2                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(4.24433093514364E-05)
#define TYPE_BASSBOOST1_B2                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_A1                             152
#define FIXPT_BASSBOOST1_A1                            0x00FDA153
#define VALUE_BASSBOOST1_A1                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98148576456209)
#define TYPE_BASSBOOST1_A1                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_A2                             153
#define FIXPT_BASSBOOST1_A2                            0xFF82591D
#define VALUE_BASSBOOST1_A2                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.981655537799498)
#define TYPE_BASSBOOST1_A2                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE0                         154
#define FIXPT_BASSBOOST1_TABLE0                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE0                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE0                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE1                         155
#define FIXPT_BASSBOOST1_TABLE1                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE1                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE1                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE2                         156
#define FIXPT_BASSBOOST1_TABLE2                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE2                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE2                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE3                         157
#define FIXPT_BASSBOOST1_TABLE3                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE3                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE3                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE4                         158
#define FIXPT_BASSBOOST1_TABLE4                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE4                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE4                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE5                         159
#define FIXPT_BASSBOOST1_TABLE5                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE5                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE5                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE6                         160
#define FIXPT_BASSBOOST1_TABLE6                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE6                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE6                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE7                         161
#define FIXPT_BASSBOOST1_TABLE7                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE7                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE7                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE8                         162
#define FIXPT_BASSBOOST1_TABLE8                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE8                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE8                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE9                         163
#define FIXPT_BASSBOOST1_TABLE9                        0x0028DA07
#define VALUE_BASSBOOST1_TABLE9                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE9                         SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE10                        164
#define FIXPT_BASSBOOST1_TABLE10                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE10                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE10                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE11                        165
#define FIXPT_BASSBOOST1_TABLE11                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE11                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE11                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE12                        166
#define FIXPT_BASSBOOST1_TABLE12                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE12                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE12                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE13                        167
#define FIXPT_BASSBOOST1_TABLE13                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE13                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE13                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE14                        168
#define FIXPT_BASSBOOST1_TABLE14                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE14                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE14                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE15                        169
#define FIXPT_BASSBOOST1_TABLE15                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE15                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE15                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE16                        170
#define FIXPT_BASSBOOST1_TABLE16                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE16                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE16                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE17                        171
#define FIXPT_BASSBOOST1_TABLE17                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE17                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE17                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE18                        172
#define FIXPT_BASSBOOST1_TABLE18                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE18                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE18                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE19                        173
#define FIXPT_BASSBOOST1_TABLE19                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE19                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE19                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE20                        174
#define FIXPT_BASSBOOST1_TABLE20                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE20                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE20                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE21                        175
#define FIXPT_BASSBOOST1_TABLE21                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE21                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE21                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE22                        176
#define FIXPT_BASSBOOST1_TABLE22                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE22                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE22                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE23                        177
#define FIXPT_BASSBOOST1_TABLE23                       0x0028DA07
#define VALUE_BASSBOOST1_TABLE23                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.319153785510076)
#define TYPE_BASSBOOST1_TABLE23                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE24                        178
#define FIXPT_BASSBOOST1_TABLE24                       0x00295321
#define VALUE_BASSBOOST1_TABLE24                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.322849412171264)
#define TYPE_BASSBOOST1_TABLE24                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE25                        179
#define FIXPT_BASSBOOST1_TABLE25                       0x002AC6E7
#define VALUE_BASSBOOST1_TABLE25                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.334195040026114)
#define TYPE_BASSBOOST1_TABLE25                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE26                        180
#define FIXPT_BASSBOOST1_TABLE26                       0x002C47BD
#define VALUE_BASSBOOST1_TABLE26                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.345939377826122)
#define TYPE_BASSBOOST1_TABLE26                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE27                        181
#define FIXPT_BASSBOOST1_TABLE27                       0x002DD61A
#define VALUE_BASSBOOST1_TABLE27                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.358096437102636)
#define TYPE_BASSBOOST1_TABLE27                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE28                        182
#define FIXPT_BASSBOOST1_TABLE28                       0x002F7277
#define VALUE_BASSBOOST1_TABLE28                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.370680721782576)
#define TYPE_BASSBOOST1_TABLE28                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE29                        183
#define FIXPT_BASSBOOST1_TABLE29                       0x00311D51
#define VALUE_BASSBOOST1_TABLE29                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.383707245492279)
#define TYPE_BASSBOOST1_TABLE29                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE30                        184
#define FIXPT_BASSBOOST1_TABLE30                       0x0032D72C
#define VALUE_BASSBOOST1_TABLE30                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.39719154946944)
#define TYPE_BASSBOOST1_TABLE30                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE31                        185
#define FIXPT_BASSBOOST1_TABLE31                       0x0034A08D
#define VALUE_BASSBOOST1_TABLE31                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.411149721104522)
#define TYPE_BASSBOOST1_TABLE31                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TABLE32                        186
#define FIXPT_BASSBOOST1_TABLE32                       0x00367A02
#define VALUE_BASSBOOST1_TABLE32                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.425598413133743)
#define TYPE_BASSBOOST1_TABLE32                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_BASSBOOST1_TIMECONSTANT                   187
#define FIXPT_BASSBOOST1_TIMECONSTANT                  0x000006D3
#define VALUE_BASSBOOST1_TIMECONSTANT                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000208311633451363)
#define TYPE_BASSBOOST1_TIMECONSTANT                   SIGMASTUDIOTYPE_FIXPOINT

/* Module 1 X RTA2_2 - Single Level Detector*/
#define COUNT_1XRTA2_2                                 5
#define DEVICE_1XRTA2_2                                "IC1"
#define ADDR_1XRTA2_2_TCONST                           188
#define FIXPT_1XRTA2_2_TCONST                          0x00004EB0
#define VALUE_1XRTA2_2_TCONST                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define TYPE_1XRTA2_2_TCONST                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA2_2_HOLD                             189
#define FIXPT_1XRTA2_2_HOLD                            0x000001E0
#define VALUE_1XRTA2_2_HOLD                            SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define TYPE_1XRTA2_2_HOLD                             SIGMASTUDIOTYPE_INTEGER
#define ADDR_1XRTA2_2_DECAY                            190
#define FIXPT_1XRTA2_2_DECAY                           0x0000071C
#define VALUE_1XRTA2_2_DECAY                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define TYPE_1XRTA2_2_DECAY                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA2_2                                  2074
#define VALUES_1XRTA2_2                                SIGMASTUDIOTYPE_SPECIAL(0x0AB2)
#define TYPE_1XRTA2_2                                  SIGMASTUDIOTYPE_SPECIAL
#define ADDR_1XRTA2_2                                  2074
#define VALUE_1XRTA2_2                                 SIGMASTUDIOTYPE_10_14_CONVERT(0)
#define TYPE_1XRTA2_2                                  SIGMASTUDIOTYPE_10_14

/* Module 1 X RTA1_2 - Single Level Detector*/
#define COUNT_1XRTA1_2                                 5
#define DEVICE_1XRTA1_2                                "IC1"
#define ADDR_1XRTA1_2_TCONST                           191
#define FIXPT_1XRTA1_2_TCONST                          0x00004EB0
#define VALUE_1XRTA1_2_TCONST                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define TYPE_1XRTA1_2_TCONST                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA1_2_HOLD                             192
#define FIXPT_1XRTA1_2_HOLD                            0x000001E0
#define VALUE_1XRTA1_2_HOLD                            SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define TYPE_1XRTA1_2_HOLD                             SIGMASTUDIOTYPE_INTEGER
#define ADDR_1XRTA1_2_DECAY                            193
#define FIXPT_1XRTA1_2_DECAY                           0x0000071C
#define VALUE_1XRTA1_2_DECAY                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define TYPE_1XRTA1_2_DECAY                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_1XRTA1_2                                  2074
#define VALUES_1XRTA1_2                                SIGMASTUDIOTYPE_SPECIAL(0x0B36)
#define TYPE_1XRTA1_2                                  SIGMASTUDIOTYPE_SPECIAL
#define ADDR_1XRTA1_2                                  2074
#define VALUE_1XRTA1_2                                 SIGMASTUDIOTYPE_10_14_CONVERT(0)
#define TYPE_1XRTA1_2                                  SIGMASTUDIOTYPE_10_14

/* Module Limiter 2 - Limiter*/
#define COUNT_LIMITER2                                 15
#define DEVICE_LIMITER2                                "IC1"
#define ADDR_LIMITER2_S1                               194
#define FIXPT_LIMITER2_S1                              0xFFFE2BE3
#define VALUE_LIMITER2_S1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define TYPE_LIMITER2_S1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT1                             195
#define FIXPT_LIMITER2_INT1                            0x0022BE2B
#define VALUE_LIMITER2_INT1                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define TYPE_LIMITER2_INT1                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_S2                               196
#define FIXPT_LIMITER2_S2                              0xFFEAAAAB
#define VALUE_LIMITER2_S2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define TYPE_LIMITER2_S2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT2                             197
#define FIXPT_LIMITER2_INT2                            0x006AAAAA
#define VALUE_LIMITER2_INT2                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define TYPE_LIMITER2_INT2                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_S3                               198
#define FIXPT_LIMITER2_S3                              0xFF9A69A7
#define VALUE_LIMITER2_S3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define TYPE_LIMITER2_S3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT3                             199
#define FIXPT_LIMITER2_INT3                            0x00FDF7DF
#define VALUE_LIMITER2_INT3                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define TYPE_LIMITER2_INT3                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_S4                               200
#define FIXPT_LIMITER2_S4                              0xF83C6C20
#define VALUE_LIMITER2_S4                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define TYPE_LIMITER2_S4                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT4                             201
#define FIXPT_LIMITER2_INT4                            0x03F5AA22
#define VALUE_LIMITER2_INT4                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define TYPE_LIMITER2_INT4                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_C1                               202
#define FIXPT_LIMITER2_C1                              0x01800000
#define VALUE_LIMITER2_C1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define TYPE_LIMITER2_C1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_C2                               203
#define FIXPT_LIMITER2_C2                              0x01000000
#define VALUE_LIMITER2_C2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define TYPE_LIMITER2_C2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_C3                               204
#define FIXPT_LIMITER2_C3                              0x00333333
#define VALUE_LIMITER2_C3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define TYPE_LIMITER2_C3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_THRESHOLD                        205
#define FIXPT_LIMITER2_THRESHOLD                       0x00800000
#define VALUE_LIMITER2_THRESHOLD                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_LIMITER2_THRESHOLD                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_RMS                              206
#define FIXPT_LIMITER2_RMS                             0x000007DC
#define VALUE_LIMITER2_RMS                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000239881380791562)
#define TYPE_LIMITER2_RMS                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_DECAY                            207
#define FIXPT_LIMITER2_DECAY                           0x00000800
#define VALUE_LIMITER2_DECAY                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define TYPE_LIMITER2_DECAY                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_DECAYCOMPLEMENT                  208
#define FIXPT_LIMITER2_DECAYCOMPLEMENT                 0x007FF000
#define VALUE_LIMITER2_DECAYCOMPLEMENT                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define TYPE_LIMITER2_DECAYCOMPLEMENT                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 1 - Limiter*/
#define COUNT_LIMITER1                                 15
#define DEVICE_LIMITER1                                "IC1"
#define ADDR_LIMITER1_S1                               209
#define FIXPT_LIMITER1_S1                              0xFFFE2BE3
#define VALUE_LIMITER1_S1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define TYPE_LIMITER1_S1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT1                             210
#define FIXPT_LIMITER1_INT1                            0x0022BE2B
#define VALUE_LIMITER1_INT1                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define TYPE_LIMITER1_INT1                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_S2                               211
#define FIXPT_LIMITER1_S2                              0xFFEAAAAB
#define VALUE_LIMITER1_S2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define TYPE_LIMITER1_S2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT2                             212
#define FIXPT_LIMITER1_INT2                            0x006AAAAA
#define VALUE_LIMITER1_INT2                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define TYPE_LIMITER1_INT2                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_S3                               213
#define FIXPT_LIMITER1_S3                              0xFF9A69A7
#define VALUE_LIMITER1_S3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define TYPE_LIMITER1_S3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT3                             214
#define FIXPT_LIMITER1_INT3                            0x00FDF7DF
#define VALUE_LIMITER1_INT3                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define TYPE_LIMITER1_INT3                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_S4                               215
#define FIXPT_LIMITER1_S4                              0xF83C6C20
#define VALUE_LIMITER1_S4                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define TYPE_LIMITER1_S4                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT4                             216
#define FIXPT_LIMITER1_INT4                            0x03F5AA22
#define VALUE_LIMITER1_INT4                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define TYPE_LIMITER1_INT4                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_C1                               217
#define FIXPT_LIMITER1_C1                              0x01800000
#define VALUE_LIMITER1_C1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define TYPE_LIMITER1_C1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_C2                               218
#define FIXPT_LIMITER1_C2                              0x01000000
#define VALUE_LIMITER1_C2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define TYPE_LIMITER1_C2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_C3                               219
#define FIXPT_LIMITER1_C3                              0x00333333
#define VALUE_LIMITER1_C3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define TYPE_LIMITER1_C3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_THRESHOLD                        220
#define FIXPT_LIMITER1_THRESHOLD                       0x00800000
#define VALUE_LIMITER1_THRESHOLD                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_LIMITER1_THRESHOLD                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_RMS                              221
#define FIXPT_LIMITER1_RMS                             0x000007DC
#define VALUE_LIMITER1_RMS                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000239881380791562)
#define TYPE_LIMITER1_RMS                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_DECAY                            222
#define FIXPT_LIMITER1_DECAY                           0x00000800
#define VALUE_LIMITER1_DECAY                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define TYPE_LIMITER1_DECAY                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_DECAYCOMPLEMENT                  223
#define FIXPT_LIMITER1_DECAYCOMPLEMENT                 0x007FF000
#define VALUE_LIMITER1_DECAYCOMPLEMENT                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define TYPE_LIMITER1_DECAYCOMPLEMENT                  SIGMASTUDIOTYPE_FIXPOINT

#endif
