/*
 * File:           C:\Users\mikbi\Documents\Allegati\Desktop\DigiRadio\DigiRadio_IC_1_PARAM.h
 *
 * Created:        Monday, July 6, 2026 2:41:28 PM
 * Description:    DigiRadio:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2026 Analog Devices, Inc. All rights reserved.
 */
#ifndef __DIGIRADIO_IC_1_PARAM_H__
#define __DIGIRADIO_IC_1_PARAM_H__


/* Module Si4674 - Multiple Volume Control*/
#define COUNT_SI4674                                   2
#define DEVICE_SI4674                                  "IC1"
#define ADDR_SI4674                                    0
#define FIXPT_SI4674                                   0x00800000
#define VALUE_SI4674                                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SI4674                                    SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_SI4674_1                                  1
#define FIXPT_SI4674_1                                 0x00800000
#define VALUE_SI4674_1                                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_SI4674_1                                  SIGMASTUDIOTYPE_FIXPOINT

/* Module ESP32 - Multiple Volume Control*/
#define COUNT_ESP32                                    2
#define DEVICE_ESP32                                   "IC1"
#define ADDR_ESP32                                     2
#define FIXPT_ESP32                                    0x00800000
#define VALUE_ESP32                                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_ESP32                                     SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_ESP32_1                                   3
#define FIXPT_ESP32_1                                  0x00800000
#define VALUE_ESP32_1                                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_ESP32_1                                   SIGMASTUDIOTYPE_FIXPOINT

/* Module St Mixer1 - Stereo Mixer*/
#define COUNT_STMIXER1                                 2
#define DEVICE_STMIXER1                                "IC1"
#define ADDR_STMIXER1_ST0_VOLUME                       4
#define FIXPT_STMIXER1_ST0_VOLUME                      0x00800000
#define VALUE_STMIXER1_ST0_VOLUME                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_STMIXER1_ST0_VOLUME                       SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_STMIXER1_ST1_VOLUME                       5
#define FIXPT_STMIXER1_ST1_VOLUME                      0x00800000
#define VALUE_STMIXER1_ST1_VOLUME                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_STMIXER1_ST1_VOLUME                       SIGMASTUDIOTYPE_FIXPOINT

/* Module Param EQ1 - Parametric EQ*/
#define COUNT_PARAMEQ1                                 60
#define DEVICE_PARAMEQ1                                "IC1"
#define ADDR_PARAMEQ1_ST0_B0                           6
#define FIXPT_PARAMEQ1_ST0_B0                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B0                           6
#define FIXPT_PARAMEQ1_ST0_B0                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B1                           7
#define FIXPT_PARAMEQ1_ST0_B1                          0xFF007936
#define VALUE_PARAMEQ1_ST0_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.9963010223809)
#define TYPE_PARAMEQ1_ST0_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B1                           7
#define FIXPT_PARAMEQ1_ST0_B1                          0xFF007936
#define VALUE_PARAMEQ1_ST0_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.9963010223809)
#define TYPE_PARAMEQ1_ST0_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B2                           8
#define FIXPT_PARAMEQ1_ST0_B2                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_B2                           8
#define FIXPT_PARAMEQ1_ST0_B2                          0x007FC365
#define VALUE_PARAMEQ1_ST0_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998150511190452)
#define TYPE_PARAMEQ1_ST0_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A0                           9
#define FIXPT_PARAMEQ1_ST0_A0                          0x00FF86AE
#define VALUE_PARAMEQ1_ST0_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99629760176912)
#define TYPE_PARAMEQ1_ST0_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A0                           9
#define FIXPT_PARAMEQ1_ST0_A0                          0x00FF86AE
#define VALUE_PARAMEQ1_ST0_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99629760176912)
#define TYPE_PARAMEQ1_ST0_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A1                           10
#define FIXPT_PARAMEQ1_ST0_A1                          0xFF807919
#define VALUE_PARAMEQ1_ST0_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.996304442992686)
#define TYPE_PARAMEQ1_ST0_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST0_A1                           10
#define FIXPT_PARAMEQ1_ST0_A1                          0xFF807919
#define VALUE_PARAMEQ1_ST0_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.996304442992686)
#define TYPE_PARAMEQ1_ST0_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B0                           11
#define FIXPT_PARAMEQ1_ST1_B0                          0x00800000
#define VALUE_PARAMEQ1_ST1_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST1_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B0                           11
#define FIXPT_PARAMEQ1_ST1_B0                          0x00800000
#define VALUE_PARAMEQ1_ST1_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST1_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B1                           12
#define FIXPT_PARAMEQ1_ST1_B1                          0x00000000
#define VALUE_PARAMEQ1_ST1_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B1                           12
#define FIXPT_PARAMEQ1_ST1_B1                          0x00000000
#define VALUE_PARAMEQ1_ST1_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B2                           13
#define FIXPT_PARAMEQ1_ST1_B2                          0x00000000
#define VALUE_PARAMEQ1_ST1_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_B2                           13
#define FIXPT_PARAMEQ1_ST1_B2                          0x00000000
#define VALUE_PARAMEQ1_ST1_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A0                           14
#define FIXPT_PARAMEQ1_ST1_A0                          0x00000000
#define VALUE_PARAMEQ1_ST1_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A0                           14
#define FIXPT_PARAMEQ1_ST1_A0                          0x00000000
#define VALUE_PARAMEQ1_ST1_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A1                           15
#define FIXPT_PARAMEQ1_ST1_A1                          0x00000000
#define VALUE_PARAMEQ1_ST1_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST1_A1                           15
#define FIXPT_PARAMEQ1_ST1_A1                          0x00000000
#define VALUE_PARAMEQ1_ST1_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST1_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B0                           16
#define FIXPT_PARAMEQ1_ST2_B0                          0x00800000
#define VALUE_PARAMEQ1_ST2_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST2_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B0                           16
#define FIXPT_PARAMEQ1_ST2_B0                          0x00800000
#define VALUE_PARAMEQ1_ST2_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST2_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B1                           17
#define FIXPT_PARAMEQ1_ST2_B1                          0x00000000
#define VALUE_PARAMEQ1_ST2_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B1                           17
#define FIXPT_PARAMEQ1_ST2_B1                          0x00000000
#define VALUE_PARAMEQ1_ST2_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B2                           18
#define FIXPT_PARAMEQ1_ST2_B2                          0x00000000
#define VALUE_PARAMEQ1_ST2_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_B2                           18
#define FIXPT_PARAMEQ1_ST2_B2                          0x00000000
#define VALUE_PARAMEQ1_ST2_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A0                           19
#define FIXPT_PARAMEQ1_ST2_A0                          0x00000000
#define VALUE_PARAMEQ1_ST2_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A0                           19
#define FIXPT_PARAMEQ1_ST2_A0                          0x00000000
#define VALUE_PARAMEQ1_ST2_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A1                           20
#define FIXPT_PARAMEQ1_ST2_A1                          0x00000000
#define VALUE_PARAMEQ1_ST2_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST2_A1                           20
#define FIXPT_PARAMEQ1_ST2_A1                          0x00000000
#define VALUE_PARAMEQ1_ST2_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST2_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B0                           21
#define FIXPT_PARAMEQ1_ST3_B0                          0x00800000
#define VALUE_PARAMEQ1_ST3_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST3_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B0                           21
#define FIXPT_PARAMEQ1_ST3_B0                          0x00800000
#define VALUE_PARAMEQ1_ST3_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST3_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B1                           22
#define FIXPT_PARAMEQ1_ST3_B1                          0x00000000
#define VALUE_PARAMEQ1_ST3_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B1                           22
#define FIXPT_PARAMEQ1_ST3_B1                          0x00000000
#define VALUE_PARAMEQ1_ST3_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B2                           23
#define FIXPT_PARAMEQ1_ST3_B2                          0x00000000
#define VALUE_PARAMEQ1_ST3_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_B2                           23
#define FIXPT_PARAMEQ1_ST3_B2                          0x00000000
#define VALUE_PARAMEQ1_ST3_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A0                           24
#define FIXPT_PARAMEQ1_ST3_A0                          0x00000000
#define VALUE_PARAMEQ1_ST3_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A0                           24
#define FIXPT_PARAMEQ1_ST3_A0                          0x00000000
#define VALUE_PARAMEQ1_ST3_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A1                           25
#define FIXPT_PARAMEQ1_ST3_A1                          0x00000000
#define VALUE_PARAMEQ1_ST3_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST3_A1                           25
#define FIXPT_PARAMEQ1_ST3_A1                          0x00000000
#define VALUE_PARAMEQ1_ST3_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST3_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B0                           26
#define FIXPT_PARAMEQ1_ST4_B0                          0x00800000
#define VALUE_PARAMEQ1_ST4_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST4_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B0                           26
#define FIXPT_PARAMEQ1_ST4_B0                          0x00800000
#define VALUE_PARAMEQ1_ST4_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST4_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B1                           27
#define FIXPT_PARAMEQ1_ST4_B1                          0x00000000
#define VALUE_PARAMEQ1_ST4_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B1                           27
#define FIXPT_PARAMEQ1_ST4_B1                          0x00000000
#define VALUE_PARAMEQ1_ST4_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B2                           28
#define FIXPT_PARAMEQ1_ST4_B2                          0x00000000
#define VALUE_PARAMEQ1_ST4_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_B2                           28
#define FIXPT_PARAMEQ1_ST4_B2                          0x00000000
#define VALUE_PARAMEQ1_ST4_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A0                           29
#define FIXPT_PARAMEQ1_ST4_A0                          0x00000000
#define VALUE_PARAMEQ1_ST4_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A0                           29
#define FIXPT_PARAMEQ1_ST4_A0                          0x00000000
#define VALUE_PARAMEQ1_ST4_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A1                           30
#define FIXPT_PARAMEQ1_ST4_A1                          0x00000000
#define VALUE_PARAMEQ1_ST4_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST4_A1                           30
#define FIXPT_PARAMEQ1_ST4_A1                          0x00000000
#define VALUE_PARAMEQ1_ST4_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST4_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B0                           31
#define FIXPT_PARAMEQ1_ST5_B0                          0x00800000
#define VALUE_PARAMEQ1_ST5_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST5_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B0                           31
#define FIXPT_PARAMEQ1_ST5_B0                          0x00800000
#define VALUE_PARAMEQ1_ST5_B0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_PARAMEQ1_ST5_B0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B1                           32
#define FIXPT_PARAMEQ1_ST5_B1                          0x00000000
#define VALUE_PARAMEQ1_ST5_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B1                           32
#define FIXPT_PARAMEQ1_ST5_B1                          0x00000000
#define VALUE_PARAMEQ1_ST5_B1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_B1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B2                           33
#define FIXPT_PARAMEQ1_ST5_B2                          0x00000000
#define VALUE_PARAMEQ1_ST5_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_B2                           33
#define FIXPT_PARAMEQ1_ST5_B2                          0x00000000
#define VALUE_PARAMEQ1_ST5_B2                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_B2                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A0                           34
#define FIXPT_PARAMEQ1_ST5_A0                          0x00000000
#define VALUE_PARAMEQ1_ST5_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A0                           34
#define FIXPT_PARAMEQ1_ST5_A0                          0x00000000
#define VALUE_PARAMEQ1_ST5_A0                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_A0                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A1                           35
#define FIXPT_PARAMEQ1_ST5_A1                          0x00000000
#define VALUE_PARAMEQ1_ST5_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_A1                           SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_PARAMEQ1_ST5_A1                           35
#define FIXPT_PARAMEQ1_ST5_A1                          0x00000000
#define VALUE_PARAMEQ1_ST5_A1                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define TYPE_PARAMEQ1_ST5_A1                           SIGMASTUDIOTYPE_FIXPOINT

/* Module Multiple 1 - Multiple Volume Control*/
#define COUNT_MULTIPLE1                                2
#define DEVICE_MULTIPLE1                               "IC1"
#define ADDR_MULTIPLE1                                 36
#define FIXPT_MULTIPLE1                                0x00800000
#define VALUE_MULTIPLE1                                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_MULTIPLE1                                 SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_MULTIPLE1_1                               37
#define FIXPT_MULTIPLE1_1                              0x00800000
#define VALUE_MULTIPLE1_1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_MULTIPLE1_1                               SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 1 - Limiter*/
#define COUNT_LIMITER1                                 15
#define DEVICE_LIMITER1                                "IC1"
#define ADDR_LIMITER1_S1                               38
#define FIXPT_LIMITER1_S1                              0xFFFE2BE3
#define VALUE_LIMITER1_S1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define TYPE_LIMITER1_S1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT1                             39
#define FIXPT_LIMITER1_INT1                            0x0022BE2B
#define VALUE_LIMITER1_INT1                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define TYPE_LIMITER1_INT1                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_S2                               40
#define FIXPT_LIMITER1_S2                              0xFFEAAAAB
#define VALUE_LIMITER1_S2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define TYPE_LIMITER1_S2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT2                             41
#define FIXPT_LIMITER1_INT2                            0x006AAAAA
#define VALUE_LIMITER1_INT2                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define TYPE_LIMITER1_INT2                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_S3                               42
#define FIXPT_LIMITER1_S3                              0xFF9A69A7
#define VALUE_LIMITER1_S3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define TYPE_LIMITER1_S3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT3                             43
#define FIXPT_LIMITER1_INT3                            0x00FDF7DF
#define VALUE_LIMITER1_INT3                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define TYPE_LIMITER1_INT3                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_S4                               44
#define FIXPT_LIMITER1_S4                              0xF83C6C20
#define VALUE_LIMITER1_S4                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define TYPE_LIMITER1_S4                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_INT4                             45
#define FIXPT_LIMITER1_INT4                            0x03F5AA22
#define VALUE_LIMITER1_INT4                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define TYPE_LIMITER1_INT4                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_C1                               46
#define FIXPT_LIMITER1_C1                              0x01800000
#define VALUE_LIMITER1_C1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define TYPE_LIMITER1_C1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_C2                               47
#define FIXPT_LIMITER1_C2                              0x01000000
#define VALUE_LIMITER1_C2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define TYPE_LIMITER1_C2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_C3                               48
#define FIXPT_LIMITER1_C3                              0x00333333
#define VALUE_LIMITER1_C3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define TYPE_LIMITER1_C3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_THRESHOLD                        49
#define FIXPT_LIMITER1_THRESHOLD                       0x00800000
#define VALUE_LIMITER1_THRESHOLD                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_LIMITER1_THRESHOLD                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_RMS                              50
#define FIXPT_LIMITER1_RMS                             0x000007DC
#define VALUE_LIMITER1_RMS                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000239881380791562)
#define TYPE_LIMITER1_RMS                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_DECAY                            51
#define FIXPT_LIMITER1_DECAY                           0x00000800
#define VALUE_LIMITER1_DECAY                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define TYPE_LIMITER1_DECAY                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER1_DECAYCOMPLEMENT                  52
#define FIXPT_LIMITER1_DECAYCOMPLEMENT                 0x007FF000
#define VALUE_LIMITER1_DECAYCOMPLEMENT                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define TYPE_LIMITER1_DECAYCOMPLEMENT                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 2 - Limiter*/
#define COUNT_LIMITER2                                 15
#define DEVICE_LIMITER2                                "IC1"
#define ADDR_LIMITER2_S1                               53
#define FIXPT_LIMITER2_S1                              0xFFFE2BE3
#define VALUE_LIMITER2_S1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define TYPE_LIMITER2_S1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT1                             54
#define FIXPT_LIMITER2_INT1                            0x0022BE2B
#define VALUE_LIMITER2_INT1                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define TYPE_LIMITER2_INT1                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_S2                               55
#define FIXPT_LIMITER2_S2                              0xFFEAAAAB
#define VALUE_LIMITER2_S2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define TYPE_LIMITER2_S2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT2                             56
#define FIXPT_LIMITER2_INT2                            0x006AAAAA
#define VALUE_LIMITER2_INT2                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define TYPE_LIMITER2_INT2                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_S3                               57
#define FIXPT_LIMITER2_S3                              0xFF9A69A7
#define VALUE_LIMITER2_S3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define TYPE_LIMITER2_S3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT3                             58
#define FIXPT_LIMITER2_INT3                            0x00FDF7DF
#define VALUE_LIMITER2_INT3                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define TYPE_LIMITER2_INT3                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_S4                               59
#define FIXPT_LIMITER2_S4                              0xF83C6C20
#define VALUE_LIMITER2_S4                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define TYPE_LIMITER2_S4                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_INT4                             60
#define FIXPT_LIMITER2_INT4                            0x03F5AA22
#define VALUE_LIMITER2_INT4                            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define TYPE_LIMITER2_INT4                             SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_C1                               61
#define FIXPT_LIMITER2_C1                              0x01800000
#define VALUE_LIMITER2_C1                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define TYPE_LIMITER2_C1                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_C2                               62
#define FIXPT_LIMITER2_C2                              0x01000000
#define VALUE_LIMITER2_C2                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define TYPE_LIMITER2_C2                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_C3                               63
#define FIXPT_LIMITER2_C3                              0x00333333
#define VALUE_LIMITER2_C3                              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define TYPE_LIMITER2_C3                               SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_THRESHOLD                        64
#define FIXPT_LIMITER2_THRESHOLD                       0x00800000
#define VALUE_LIMITER2_THRESHOLD                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define TYPE_LIMITER2_THRESHOLD                        SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_RMS                              65
#define FIXPT_LIMITER2_RMS                             0x000007DC
#define VALUE_LIMITER2_RMS                             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000239881380791562)
#define TYPE_LIMITER2_RMS                              SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_DECAY                            66
#define FIXPT_LIMITER2_DECAY                           0x00000800
#define VALUE_LIMITER2_DECAY                           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define TYPE_LIMITER2_DECAY                            SIGMASTUDIOTYPE_FIXPOINT
#define ADDR_LIMITER2_DECAYCOMPLEMENT                  67
#define FIXPT_LIMITER2_DECAYCOMPLEMENT                 0x007FF000
#define VALUE_LIMITER2_DECAYCOMPLEMENT                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define TYPE_LIMITER2_DECAYCOMPLEMENT                  SIGMASTUDIOTYPE_FIXPOINT

#endif
